export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  resendApiKey: process.env.RESEND_API_KEY ?? "",
  shipstationApiKey: process.env.SHIPSTATION_API_KEY ?? "",
  shipstationApiSecret: process.env.SHIPSTATION_API_SECRET ?? "",
  liveEmailEnabled: process.env.ENABLE_LIVE_EMAIL === "true",
  liveShipstationEnabled: process.env.ENABLE_LIVE_SHIPSTATION === "true",
};
